name: Upload SBOM for dependabot

on: 
  workflow_dispatch:
  push: 
    branches: ["main"]

jobs:
  upload-sbom:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Generate SBOM
      run: | 
        curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
        chmod +x $RUNNER_TEMP/sbom-tool
        $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn rehash -pv 1.0.0 -ps thekatze -nsb https://thekatze.com/rehash -V Verbose
    - uses: actions/upload-artifact@v3
      with:
        name: sbom
        path: _manifest/spdx_2.2

    - name: Upload SBOM
      uses: jonathborg/spdx-to-dependency-graph-action@v1.0.1
      with:
        filePath: "_manifest/spdx_2.2/"
